### ISSUE TITLE
Feature Request: Option to rewrite source ip dynamically to match incoming packet source address

### ISSUE THREAD

**Issue by technomancer-101** [hwipl/bcast-forward#1]
Hi there,

I'd like to start with THANK YOU. Your program allows us to run some client software over a VPN that inexplicably uses a broadcast packet to locate its host server every single time you open it.

Any chance you would be able to implement an option for the source IP to be dynamically rewritten based on the origin of the broadcast packet? Everything works great as-is, but I can only use it for one host at a time. I would love to help out, but unfortunately I don't know Go.

Thanks.

**Comment by hwipl** [comment]
Hey, thanks for the positive feedback :)

Just to make sure I understand your request correctly: You want to run the program on some host in your network. It receives broadcast packets from other hosts in the network and forwards them over a VPN tunnel. Reply packets could go directly from the VPN tunnel to the original hosts, but the source address rewriting gets into your way (for more than one other host). So, you would basically need an option to just keep the original source IP address in the packets, right?

**Comment by technomancer-101** [comment]
Yep, you got it. That's exactly what I'm hoping for.  
Other than the fact that it can only point at one original IP right now, it's working perfectly. 

Thanks again :)

**Comment by hwipl** [comment]
I added the command line argument "-keep-source-ip" that should disable the source address rewriting. Could you test if it works for you?

**Comment by technomancer-101** [comment]
Testing looks good. Opened our client from a handful of computers simultaneously and all packets are relaying correctly between the server and each client respectively.
Thank you again, this helps us a lot!

**Comment by hwipl** [comment]
Great, closing this issue for now. If anything breaks, feel free to re-open or create a new one :)
