### ISSUE TITLE
bcast-forward command not found

### ISSUE THREAD

**Issue by k4r3l01** [hwipl/bcast-forward#2]
Hello please i tried to install this tool to my ubuntu server but when i try to use command bcast-forward so server gives me command not found

**Comment by hwipl** [comment]
Go installs the binary to your $GOBIN directory. Probably you can find it in `$HOME/go/bin`.
See https://pkg.go.dev/cmd/go#hdr-Compile_and_install_packages_and_dependencies

**Comment by hwipl** [comment]
I assume this resolved the issue, closing
